version: 2
jobs:
  test:
    docker:
      # specify the version you desire here
      - image: circleci/node:9.3

    working_directory: ~/react-babel-webpack

    steps:
      - checkout
      - run:
          name: Just to make a job before
          command: echo "Hello World"
  deploy:
    environment:
      HEROKU_APP_NAME: "react-babel-webpack"
    working_directory: ~/react-babel-webpack
    docker:
      # specify the version you desire here
      - image: circleci/node:9.3
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "cc:40:d1:99:63:e0:1f:cb:6f:0c:32:7b:be:22:2c:87"
      - run:
          name: Setup Heroku
          command: bash .circleci/setup-heroku.sh
      - run:
          name: npm Install
          command: npm install
      - run:
          name: npm Install
          command: npm run build
      - run:
          name: Deploy Master to Heroku
          command: |
            heroku git:remote -a $HEROKU_APP_NAME
            git push --force git@heroku.com:$HEROKU_APP_NAME.git HEAD:refs/heads/master
            # heroku run npm install
            # heroku run npm run build
            sleep 5
            heroku restart
workflows:
  version: 2
  build-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master



